name: musicfinder
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.0.5
  intl: ^0.20.2
  table_calendar: ^3.2.0
  google_maps_flutter: ^2.10.0
  flutter_map: ^8.0.0
  flutter_datetime_picker: ^1.5.1
  latlong2: ^0.9.1
  shared_preferences: ^2.0.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  webview_flutter: ^4.0.0
  flutter_paypal: ^0.2.1 # Añade esta línea
  flutter_stripe: ^11.4.0
  flutter_paypal_payment: ^1.0.7
  flutter_animate: ^4.5.2
  path_provider: ^2.1.5
  firebase_core: ^2.3.0
  firebase_auth: ^4.5.0 # Si deseas usar autenticación
  cloud_firestore: ^4.5.0 # Si deseas usar Firestore
  


 



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/guitar_teacher.jpg
    - assets/piano_teacher.jpg
    - assets/violin_teacher.jpg
    - assets/student.jpg
    - assets/payment_profile.json 
    - assets/images/Illustration.jpg